#-------------------------------
# Site Settings
title: Heegi Yun
logo: # You can add own logo. For example '/images/logo.png'.
author: Heegi Yun
description: This is Heegi's UX portfolio website.


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'About'
      url: '/about/'
    - title: 'Resume'
      url: '/files/Heegi_Resume.pdf'


#-------------------------------
# Hero Settings
hero:
  hero__title: Hi, I'm Heegi <br> a UX Researcher <br> based in Oakland, CA
  hero__description: I recently graduated with an <b>M.S. in Human Factors and Ergonomics</b> with a focus in Human-Computer Interaction (HCI) at San Jose State University.


#-------------------------------
# Footer Settings
social:
- {label: LinkedIn, link: "https://www.linkedin.com/in/heegi-yun/"}
- {label: Email, link: "mailto:contact@heegiyun.com"}

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.