#-------------------------------
# Site Settings
title: Heegi Yun
logo: '/images/logo.png'
author: Heegi Yun
description: This is Heegi's UX portfolio website.


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'About'
      url: '/about/'
    - title: 'Resume'
      url: '/files/Heegi_Resume.pdf'


#-------------------------------
# Hero Settings
hero:
  hero__title: Hi there!
  hero__description: I'm a <b style="color:#545ed4">UX Designer</b> dedicated to solving complex problems through <b style="color:#545ed4">user research</b> and <b style="color:#545ed4">data-driven design</b>.<br><br> Currently, I work as a <b>Human Factors Engineer</b> at <b>General Dynamics Information Technology</b>, delivering comprehensive design and research works for the Centers for Medicare & Medicaid Services (CMS) client.


#-------------------------------
# Footer Settings
social:
- {label: LinkedIn, link: "https://www.linkedin.com/in/heegi-yun/"}
- {label: Email, link: "mailto:heegi.work@gmail.com"}

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.